name: http_annotation
description: Dart annotations for generating type-safe HTTP REST clients with automatic JSON serialization and parameter handling.
version: 0.0.1
repository: https://github.com/TekExplorer/http_generator
license: BSD-3-Clause
topics:
  - http
  - client
  - annotation
  - rest
  - api

resolution: workspace

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ^1.17.0
  http: ^1.6.0
  # http: ^1.5.0
  
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
